---

- name: Create Logstash configuration files.
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 00-create_index-input.conf
    - 01-companies_parts-input.conf
    - 02-pension_funds-input.conf
    - 03-tamal_statistics-input.conf
    - 04-companies-input.conf
    - 30-elasticsearch-output.conf
  when: logstash_setup_default_config
  notify: restart logstash
  tags: configuration

- name: Copy log4j2.properties to /etc/logstash/
  copy:
    src: log4j2.properties
    dest: /etc/logstash/
    owner: root
    group: root
    mode: '0644'
    backup: true
  tags: installation

- name: Copy statements folder
  copy:
    src: statements/
    dest: "{{ logstash_last_run_statement_basepath }}/"
    owner: logstash
    group: logstash
    mode: '0755'
  tags: always
