---
- name: Health check api admin
  ansible.builtin.uri:
    url: "http://localhost:{{ app_configurations['replication.http.port'] }}/healthcheck"
    follow_redirects: none
    method: GET
  register: _result
  failed_when: false
  until: _result.status == 200
  retries: 3
  delay: 5
  changed_when: false