---

- name: Copy resources
  ansible.builtin.copy:
    src: resources/
    dest: "{{ app_resources_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0750"
  notify: restart pension
  tags: installation

- name: Copy c3p0 config
  ansible.builtin.copy:
    src: c3p0-config.xml
    dest: "{{ app_lib_path }}"
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: "0750"
  tags: installation

- name: Copy keystore file with read-only permission
  ansible.builtin.get_url:
    url: "{{ internal_base_url }}/keystore/keystore.jceks"
    dest: "{{ app_jceks_keystore_path }}"
    mode: '0400'
    owner: "{{ app_user }}"
  tags: configuration

- name: Download pension from http
  ansible.builtin.get_url:
    dest: "{{ app_lib_path }}"
    url: "{{ app_jar_url }}"
    mode: "0750"
    validate_certs: false
    force: false
  when: app_jar_url.startswith("http")
  notify: restart pension
  tags: configuration

- name: Download pension from s3
  ansible.builtin.command: "aws s3 cp {{ app_jar_url }} {{ app_lib_path }}"
  when: app_jar_url.startswith("s3")
  notify: restart pension
  tags: configuration

- name: Download amazon.properties from remote server
  ansible.builtin.get_url:
    url: "{{ app_amazon_properties_remote_path }}"
    dest: "{{ app_amazon_properties_local_path }}"
    mode: '0640'
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    validate_certs: yes
  register: download_amazon_properties
  failed_when: false
  tags: configuration

- name: Log if amazon.properties not downloaded
  ansible.builtin.debug:
    msg: "amazon.properties not found on internal server."
  when: download_amazon_properties.failed
  tags: configuration

- name: Change owner for lib
  ansible.builtin.file:
    path: "{{ app_lib_path }}"
    state: directory
    recurse: true
    group: "{{ app_group }}"
    owner: "{{ app_user }}"
    mode: "0750"
  tags: configuration
